cp temp/Abstract.tex  ./tex/Abstract/
cp temp/Introduction.tex  ./tex/Introduction/
cp temp/Detector.tex   ./tex/Detector/
cp temp/ObjectDef.tex  ./tex/ObjectDef/
cp temp/Samples.tex   ./tex/Samples/
cp temp/SRdefinition.tex   ./tex/SRdefinition/
cp temp/BGestimation.tex   ./tex/BGestimation/
cp temp/Uncertainties.tex  ./tex/Uncertainties/
cp temp/Result.tex   ./tex/Result/Result.tex 
cp temp/Conclusion.tex  ./tex/Conclusion/Conclusion.tex 
